### ISSUE TITLE
Design and implement a consistent area for the magazine title, volume, release date

### ISSUE THREAD

**Issue by misscs** [cosola-salvia/news.macile.org#83]
We need to display magazine title, volume, and release dates consistently between the newsletter and bulletins. Ideally we want to display the same information consistently on the newsletter and the bulletin.

- [x] Make a few sketches/low fidelity prototype of possible options to add to the header and footer
 - Take into consideration horizontal and vertical spacing of the content. Currently the Spanish section gets cut off / content is too close to the edges
- [x] Share sketches with the team for selection
- [x] Implement

## Examples of the content
This is the example of the type of content we can expect to have for each digital magazine.

### Newsletter

- We are the heroes 
- July - October 
- MACILE Newsletter

### Bulletin

- We are the adventurers
- Dateline
- Volume
- MACILE Academy Bulletin

## Note

We will likely need to make two PRs.

1. Against `dev` to update the newlestter
1. Against `release-bulletin-v1`

**Comment by Morban15** [comment]
## 1
![20200422_094346](https://user-images.githubusercontent.com/29107510/79989426-d5256e80-847d-11ea-80f7-6447377a7cdb.jpg)

![20200422_112228](https://user-images.githubusercontent.com/29107510/80002257-67813e80-848d-11ea-8b94-5ff2a5f9d167.jpg)

## 1.2

![20200422_095343](https://user-images.githubusercontent.com/29107510/79990581-3a2d9400-847f-11ea-9dab-4b32b302e9c7.jpg)

![20200422_111800](https://user-images.githubusercontent.com/29107510/80002278-6ea84c80-848d-11ea-9f1f-3dea157faf05.jpg)

## 2

![20200422_104544](https://user-images.githubusercontent.com/29107510/79996646-ad86d400-8486-11ea-956b-21041bbc4710.jpg)

![20200422_113305](https://user-images.githubusercontent.com/29107510/80002200-5801f580-848d-11ea-9b0d-b1dd625dc68e.jpg)

## 2.2

![20200422_110154](https://user-images.githubusercontent.com/29107510/80002305-7536c400-848d-11ea-926c-2b89fac2ebcc.jpg)

![20200422_113004](https://user-images.githubusercontent.com/29107510/80002229-618b5d80-848d-11ea-9914-9f19decf03c1.jpg)

**Comment by Morban15** [comment]
![20200422_095343](https://user-images.githubusercontent.com/29107510/79990581-3a2d9400-847f-11ea-9dab-4b32b302e9c7.jpg)

**Comment by misscs** [comment]
Nice first option. Can you also include small screen version, such as mobile phone? Thanks!

**Comment by Morban15** [comment]
@misscs @cosola @MariaGuillen @lehysen 
Ya está.

**Comment by misscs** [comment]
Constructively, I am not convinced by any of the directions. The first direction, to me, feels like the same design that is currently on the bulletin. This design, to me, has issues because it feels like navigation the way the items are spaced out. 

The second design, where the content is stacked, is better, because the stacked text is close together which establishes that they are related. This feels closer to the right direction, but still warrants exploration. The take away being, stacking the content together helps draw association/relatedness. 

However, I still think this needs more exploration. Design is about exploration and I don't see exploration in your sketches. Break things, try new things. Don't be afraid to be bold. It is just a sketch. 

**You should feel free to rethink the whole header.** Maybe the language nav isn't in the right space? Maybe the MACILE logo and title are too big and take up too much space? What if we added the  meta information (what I"m calling the date, vol, newsletter title) above the language nav? What if we made information for COSOLA smaller in the footer, maybe it doesn't need that much priority, and by doing that we can better accommodate the new information?

Do some research, take a look at how other online journals and magazines handle their headers and footers Maybe you can't find a direct example, but you may find a design that opens up an idea. 

### Some places to start for inspiration

- [Dribbble](https://dribbble.com/)— sign up for an account (you can connect via your github). This is a wonderful community of designers that share their work. You can search by tags, like _online magazine_, _magazine_ etc
- Search for "best online magazines" or  "best designed online magazines" that should bring up a lot of lists where people collect their favorite designs
- [This magazine](https://nplusonemag.com/magazine/) just lists issue but I like how they design the list page (inspiration for later)

There's a bit to start your explorations. Get creative. Play around. Don't be afraid to make a radical change.

**Comment by misscs** [comment]
#### 27-04 standup

- @Morban15 still trying to find designs for inpsiration
- @misscs added to the issue to help find designs

**Comment by misscs** [comment]
#### 30-04 standup

- MR to upload more sketches

**Comment by Morban15** [comment]
## Without changing the header

![20200430_170756](https://user-images.githubusercontent.com/29107510/80760816-858f1480-8b07-11ea-9a1d-bd7c3088de31.jpg)

## Some changes

![20200430_170700](https://user-images.githubusercontent.com/29107510/80760919-a9eaf100-8b07-11ea-9a7e-937360488fc2.jpg)

I think we don't need the button due to it doesn't have a function (por lo menos ahora)

![20200430_170850](https://user-images.githubusercontent.com/29107510/80760786-790abc00-8b07-11ea-9e3c-49145c1e3cbe.jpg)

## :|

![sketch-1](https://user-images.githubusercontent.com/29107510/80761516-b9b70500-8b08-11ea-9524-29cbc7b2f1eb.png)

![sketch-3](https://user-images.githubusercontent.com/29107510/80761550-c6d3f400-8b08-11ea-9541-87e300b8097a.png)

![sketch-2](https://user-images.githubusercontent.com/29107510/80761533-c176a980-8b08-11ea-8061-4d493595cd50.png)

Este me gusta más

![sketch-4](https://user-images.githubusercontent.com/29107510/80761571-ccc9d500-8b08-11ea-9654-9d6dc21cd1a5.png)

![sketch-5](https://user-images.githubusercontent.com/29107510/80761577-d0f5f280-8b08-11ea-9daa-4c02610962f7.png)


## Footer

![20200430_171425](https://user-images.githubusercontent.com/29107510/80760777-74460800-8b07-11ea-9dcd-b501ba7ed1e7.jpg)

**Comment by Morban15** [comment]
I am open-minded @misscs @cosola @MariaGuillen @lehysen

**Comment by cosola** [comment]
Great job @Morban15 !
* From last 5, the first and last 2 look very nice. I prefer the first 2 with minor modifications:
1.  Adding the word MACILE  (could be next to the logo)
2.  Adding the year after July-October
3. Removing Vol 1  (I don't see it as necessary).

**Comment by misscs** [comment]
🎨 mucho más dinámico e interesante. gracais por darle otra vuelta. Fue difícil elegir. Definitivamente creo que mover el sello a equina izquierda fue una buena decisión. También quitar el slogan. 

> Este me gusta más
> 
> ![sketch-4](https://user-images.githubusercontent.com/29107510/80761571-ccc9d500-8b08-11ea-9654-9d6dc21cd1a5.png)
> 
> ![sketch-5](https://user-images.githubusercontent.com/29107510/80761577-d0f5f280-8b08-11ea-9daa-4c02610962f7.png)

Coincido! No sé bien si se debe tener la categoría de la publicación (Newsletter o Bullentin) a la izquierda y la fecha + vol a la derecha. O que siempre empieza con la categoría y después vol fecha. Esas cosas sen pueden experimentar ya en el navegador. 

Me gusta cómo agregaste el logo al foto. Todavía siento que hay mucha información y se pierde un poco porque todo está centralizado.

**Comment by misscs** [comment]
Change the header text in the newsletter to: _Conquered steps are milestones on the journeys we're pursuing. We're forging ahead!_

**Comment by misscs** [comment]
Changes to the header discussed and finalized during standup....

<img width="629" alt="Screen Shot 2020-05-04 at 10 59 58" src="https://user-images.githubusercontent.com/51812/80980321-80c3ac80-8df6-11ea-9cde-4d0d18e31613.png">

Consensus over keeping the dark blue background in the header.

**Comment by Morban15** [comment]
### Design implemented

![new-header-design](https://user-images.githubusercontent.com/29107510/81119008-f4011780-8ef7-11ea-9af6-ade86c8bc383.png)

### For mobile, which one is better?

![new-header-design-first-option](https://user-images.githubusercontent.com/29107510/81118529-10e91b00-8ef7-11ea-851d-7b3b2abf6013.png)

![new-header-design-second-option](https://user-images.githubusercontent.com/29107510/81118557-1e9ea080-8ef7-11ea-9b5c-368b15e12ca7.png)

![new-header-design-third-option](https://user-images.githubusercontent.com/29107510/81118563-21999100-8ef7-11ea-8504-7e54870393bb.png)

![new-header-design-fourth-option](https://user-images.githubusercontent.com/29107510/81118540-16defc00-8ef7-11ea-97cb-45b7807aac3a.png)

**Comment by misscs** [comment]
#### standup 06-05

- Please add "MACILE Newsletter" in the header, take a screenshot and share. Then add it above the magazine title, take a screenshot and share.

- Please add the year
- Increase the font size of the subtitle
- Use abbreviations in the language menu ( EN | ES)

**Comment by Morban15** [comment]
### Modifications

![new-header-design-mod-2](https://user-images.githubusercontent.com/29107510/81201693-902c2c80-8f93-11ea-83f2-9caca9d0a76a.png)

![new-header-design-mod-3](https://user-images.githubusercontent.com/29107510/81201710-95897700-8f93-11ea-8705-442287448a9b.png)

![new-header-design-mod-2-1](https://user-images.githubusercontent.com/29107510/81217398-8cf06b00-8faa-11ea-84b9-b6dffc0e6250.png)


@misscs @cosola

**Comment by misscs** [comment]
@Morban15 falta la versión donde agregas _MACILE Newsletter_ arriba del titulo en el header con MACILE en el titulo. puedes subir esa también? Gracias.

**Comment by misscs** [comment]
ah, también necesitas unas capturas de pantallas pequeñas! 📱

**Comment by Morban15** [comment]
### For mobile

![new-header-design-mod-first](https://user-images.githubusercontent.com/29107510/81219631-0b024100-8fae-11ea-81bf-6aa6950464b5.png)

**Comment by misscs** [comment]
Vamos a usar la versión con MACILE Newsletter en el header. Tenemos que agregar MACILE en la nav.

**Comment by Morban15** [comment]
![_20200514_095844](https://user-images.githubusercontent.com/29107510/81943561-8923a080-95c9-11ea-8233-2ef4c60755cb.JPG)

**Comment by cosola** [comment]
@Morban15 , @misscs , @MariaGuillen , @lehysen ,  I see no need for more design examples. 

* The decision for the magazine front page was already made. All that is left, as I understand it, is to implement the design. 

*  The header for the bulletin, as I explained to the students and MR understood, according to this example drawing, follows similar design. The differences: 

(1) No full page background image and scrolling behavior, as in the case of the magazine; 

(2) A specified height for the header, which should be sufficient to enhance the text sizes and provide a nice presentation for the bulletin;

(3) The background could be a color from the pallet or an image. However, for this particular issue, an image may not work well since there already is a hero image. Thus, I suggest a nice background color, which could be just white;

(4) Text color or colors, which could be selected from the pallet if blue is not preferred. 

**Note:** I suggest we consider a representative background image for future editions of the summer academy bulletins; one that clearly speaks (without help of words) of the type of program, like a group of students engaging in an activity, or wearing the t-shirt for the program.  For now, I feel it is better we conclude this process.


Hope this help resolve any confusion. Let's get this done!

Thanks.  @cosola
